# Generated by Django 2.2.5 on 2020-05-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200518_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='users.Job'),
        ),
    ]
