# Generated by Django 2.2.5 on 2020-05-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200518_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='job', to='users.Job'),
        ),
    ]
