# Generated by Django 2.2.5 on 2020-05-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200518_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='users.Job'),
        ),
    ]
