# Generated by Django 2.2.5 on 2020-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200519_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(default='fb7d87fc1c264429833f', max_length=20),
        ),
    ]
