# Generated by Django 2.2.5 on 2020-05-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_users'),
        ('users', '0012_auto_20200520_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='desired_organization',
            field=models.ManyToManyField(blank=True, related_name='desired_organization', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(default='b812b4e984564f9cb9ca', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
