# Generated by Django 2.2.5 on 2020-05-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200520_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(default='1a644bc19a204928b09d', max_length=20),
        ),
    ]
