# Generated by Django 2.2.5 on 2020-05-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200520_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(default='51fad84263fe4e178609', max_length=20),
        ),
    ]
