# Generated by Django 2.2.5 on 2020-05-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200520_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(default='8524c776225545fa9899', max_length=20),
        ),
    ]
