# Generated by Django 2.2.5 on 2020-05-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200521_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(blank=True, default='bdc465424e4c4af4adbf', max_length=20),
        ),
    ]
