# Generated by Django 2.2.5 on 2020-05-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200522_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_secret',
            field=models.CharField(blank=True, default='d1977358a21c40ac8c03', max_length=20),
        ),
    ]
