# Generated by Django 2.2.5 on 2020-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20200520_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='isrecruited',
            field=models.BooleanField(default=True),
        ),
    ]
