# Generated by Django 2.2.5 on 2020-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(default='2020-05-18'),
        ),
    ]
