# Generated by Django 2.2.5 on 2020-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200518_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='question3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='question4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='question5',
            field=models.BooleanField(default=False),
        ),
    ]
