# Generated by Django 2.2.5 on 2020-05-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20200518_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='survey',
            name='question1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='question2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='question3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='question4',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
