# Generated by Django 2.2.5 on 2020-05-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20200518_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(default='2020-05-19'),
        ),
    ]
