# Generated by Django 2.2.5 on 2020-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20200519_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(default='2020-05-20'),
        ),
    ]
