# Generated by Django 2.2.5 on 2020-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20200521_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(default='2020-05-22'),
        ),
    ]
